name: twinkle
region: nyc
features:
  - buildpack-stack=ubuntu-22

# App-level environment variables (inherited by all components)
envs:
  - key: REDIS_URL
    scope: RUN_TIME
    type: SECRET
  - key: RPC_URL
    scope: RUN_TIME
    type: SECRET
  - key: PONDER_RPC_URL_11155111
    scope: RUN_TIME
    type: SECRET
  - key: FACILITATOR_PRIVATE_KEY
    scope: RUN_TIME
    type: SECRET

services:
  # REST API
  - name: api
    github:
      repo: Miny-Labs/twinkle
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /api
    envs:
      - key: SERVICE
        value: api
      - key: API_PORT
        value: "8080"
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}

  # x402 Facilitator
  - name: facilitator
    github:
      repo: Miny-Labs/twinkle
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /facilitator
    envs:
      - key: SERVICE
        value: facilitator
      - key: FACILITATOR_PORT
        value: "8080"
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: CHAIN_ID
        value: "11155111"
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}

# Workers (no HTTP)
workers:
  - name: indexer
    github:
      repo: Miny-Labs/twinkle
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: SERVICE
        value: indexer
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: CHAIN_ID
        value: "11155111"
      - key: START_BLOCK
        value: "10016000"
      - key: PONDER_DATABASE_URL
        value: ${db.DATABASE_URL}

databases:
  - name: db
    engine: PG
    production: false
